from .displacement_map_node import NODE_CLASS_MAPPINGS as DISP_MAP_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as DISP_MAP_NAME_MAPPINGS
from .logo_displacement_node import NODE_CLASS_MAPPINGS as LOGO_DISP_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as LOGO_DISP_NAME_MAPPINGS

# Combine mappings for all nodes
NODE_CLASS_MAPPINGS = {**DISP_MAP_MAPPINGS, **LOGO_DISP_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**DISP_MAP_NAME_MAPPINGS, **LOGO_DISP_NAME_MAPPINGS}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
